name: Money
targets:
  Money:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Money
        excludes:
          - "ios/**"


    settings:
      base:
        PRODUCT_NAME: Money
        PRODUCT_BUNDLE_IDENTIFIER: app.10x.money
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: 'money'
        INFOPLIST_KEY_CFBundleName: 'money'
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: 'UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight'
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: 'UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight'
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        SWIFT_EMIT_LOC_STRINGS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ALWAYS_SEARCH_USER_PATHS: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
